// Données des 114 sourates du Coran
export interface SurahData {
  number: number;
  name: string;
  nameArabic: string;
  versesCount: number;
  revelationType: 'meccan' | 'medinan';
}

export const SURAHS_DATA: SurahData[] = [
  { number: 1, name: "Al-Fatiha", nameArabic: "الفاتحة", versesCount: 7, revelationType: "meccan" },
  { number: 2, name: "Al-Baqarah", nameArabic: "البقرة", versesCount: 286, revelationType: "medinan" },
  { number: 3, name: "Aal-E-Imran", nameArabic: "آل عمران", versesCount: 200, revelationType: "medinan" },
  { number: 4, name: "An-Nisa", nameArabic: "النساء", versesCount: 176, revelationType: "medinan" },
  { number: 5, name: "Al-Ma'idah", nameArabic: "المائدة", versesCount: 120, revelationType: "medinan" },
  { number: 6, name: "Al-An'am", nameArabic: "الأنعام", versesCount: 165, revelationType: "meccan" },
  { number: 7, name: "Al-A'raf", nameArabic: "الأعراف", versesCount: 206, revelationType: "meccan" },
  { number: 8, name: "Al-Anfal", nameArabic: "الأنفال", versesCount: 75, revelationType: "medinan" },
  { number: 9, name: "At-Tawbah", nameArabic: "التوبة", versesCount: 129, revelationType: "medinan" },
  { number: 10, name: "Yunus", nameArabic: "يونس", versesCount: 109, revelationType: "meccan" },
  { number: 11, name: "Hud", nameArabic: "هود", versesCount: 123, revelationType: "meccan" },
  { number: 12, name: "Yusuf", nameArabic: "يوسف", versesCount: 111, revelationType: "meccan" },
  { number: 13, name: "Ar-Ra'd", nameArabic: "الرعد", versesCount: 43, revelationType: "medinan" },
  { number: 14, name: "Ibrahim", nameArabic: "إبراهيم", versesCount: 52, revelationType: "meccan" },
  { number: 15, name: "Al-Hijr", nameArabic: "الحجر", versesCount: 99, revelationType: "meccan" },
  { number: 16, name: "An-Nahl", nameArabic: "النحل", versesCount: 128, revelationType: "meccan" },
  { number: 17, name: "Al-Isra", nameArabic: "الإسراء", versesCount: 111, revelationType: "meccan" },
  { number: 18, name: "Al-Kahf", nameArabic: "الكهف", versesCount: 110, revelationType: "meccan" },
  { number: 19, name: "Maryam", nameArabic: "مريم", versesCount: 98, revelationType: "meccan" },
  { number: 20, name: "Ta-Ha", nameArabic: "طه", versesCount: 135, revelationType: "meccan" },
  { number: 21, name: "Al-Anbiya", nameArabic: "الأنبياء", versesCount: 112, revelationType: "meccan" },
  { number: 22, name: "Al-Hajj", nameArabic: "الحج", versesCount: 78, revelationType: "medinan" },
  { number: 23, name: "Al-Mu'minun", nameArabic: "المؤمنون", versesCount: 118, revelationType: "meccan" },
  { number: 24, name: "An-Nur", nameArabic: "النور", versesCount: 64, revelationType: "medinan" },
  { number: 25, name: "Al-Furqan", nameArabic: "الفرقان", versesCount: 77, revelationType: "meccan" },
  { number: 26, name: "Ash-Shu'ara", nameArabic: "الشعراء", versesCount: 227, revelationType: "meccan" },
  { number: 27, name: "An-Naml", nameArabic: "النمل", versesCount: 93, revelationType: "meccan" },
  { number: 28, name: "Al-Qasas", nameArabic: "القصص", versesCount: 88, revelationType: "meccan" },
  { number: 29, name: "Al-Ankabut", nameArabic: "العنكبوت", versesCount: 69, revelationType: "meccan" },
  { number: 30, name: "Ar-Rum", nameArabic: "الروم", versesCount: 60, revelationType: "meccan" },
  { number: 31, name: "Luqman", nameArabic: "لقمان", versesCount: 34, revelationType: "meccan" },
  { number: 32, name: "As-Sajdah", nameArabic: "السجدة", versesCount: 30, revelationType: "meccan" },
  { number: 33, name: "Al-Ahzab", nameArabic: "الأحزاب", versesCount: 73, revelationType: "medinan" },
  { number: 34, name: "Saba", nameArabic: "سبإ", versesCount: 54, revelationType: "meccan" },
  { number: 35, name: "Fatir", nameArabic: "فاطر", versesCount: 45, revelationType: "meccan" },
  { number: 36, name: "Ya-Sin", nameArabic: "يس", versesCount: 83, revelationType: "meccan" },
  { number: 37, name: "As-Saffat", nameArabic: "الصافات", versesCount: 182, revelationType: "meccan" },
  { number: 38, name: "Sad", nameArabic: "ص", versesCount: 88, revelationType: "meccan" },
  { number: 39, name: "Az-Zumar", nameArabic: "الزمر", versesCount: 75, revelationType: "meccan" },
  { number: 40, name: "Ghafir", nameArabic: "غافر", versesCount: 85, revelationType: "meccan" },
  { number: 41, name: "Fussilat", nameArabic: "فصلت", versesCount: 54, revelationType: "meccan" },
  { number: 42, name: "Ash-Shura", nameArabic: "الشورى", versesCount: 53, revelationType: "meccan" },
  { number: 43, name: "Az-Zukhruf", nameArabic: "الزخرف", versesCount: 89, revelationType: "meccan" },
  { number: 44, name: "Ad-Dukhan", nameArabic: "الدخان", versesCount: 59, revelationType: "meccan" },
  { number: 45, name: "Al-Jathiyah", nameArabic: "الجاثية", versesCount: 37, revelationType: "meccan" },
  { number: 46, name: "Al-Ahqaf", nameArabic: "الأحقاف", versesCount: 35, revelationType: "meccan" },
  { number: 47, name: "Muhammad", nameArabic: "محمد", versesCount: 38, revelationType: "medinan" },
  { number: 48, name: "Al-Fath", nameArabic: "الفتح", versesCount: 29, revelationType: "medinan" },
  { number: 49, name: "Al-Hujurat", nameArabic: "الحجرات", versesCount: 18, revelationType: "medinan" },
  { number: 50, name: "Qaf", nameArabic: "ق", versesCount: 45, revelationType: "meccan" },
  { number: 51, name: "Adh-Dhariyat", nameArabic: "الذاريات", versesCount: 60, revelationType: "meccan" },
  { number: 52, name: "At-Tur", nameArabic: "الطور", versesCount: 49, revelationType: "meccan" },
  { number: 53, name: "An-Najm", nameArabic: "النجم", versesCount: 62, revelationType: "meccan" },
  { number: 54, name: "Al-Qamar", nameArabic: "القمر", versesCount: 55, revelationType: "meccan" },
  { number: 55, name: "Ar-Rahman", nameArabic: "الرحمن", versesCount: 78, revelationType: "medinan" },
  { number: 56, name: "Al-Waqi'ah", nameArabic: "الواقعة", versesCount: 96, revelationType: "meccan" },
  { number: 57, name: "Al-Hadid", nameArabic: "الحديد", versesCount: 29, revelationType: "medinan" },
  { number: 58, name: "Al-Mujadila", nameArabic: "المجادلة", versesCount: 22, revelationType: "medinan" },
  { number: 59, name: "Al-Hashr", nameArabic: "الحشر", versesCount: 24, revelationType: "medinan" },
  { number: 60, name: "Al-Mumtahanah", nameArabic: "الممتحنة", versesCount: 13, revelationType: "medinan" },
  { number: 61, name: "As-Saf", nameArabic: "الصف", versesCount: 14, revelationType: "medinan" },
  { number: 62, name: "Al-Jumu'ah", nameArabic: "الجمعة", versesCount: 11, revelationType: "medinan" },
  { number: 63, name: "Al-Munafiqun", nameArabic: "المنافقون", versesCount: 11, revelationType: "medinan" },
  { number: 64, name: "At-Taghabun", nameArabic: "التغابن", versesCount: 18, revelationType: "medinan" },
  { number: 65, name: "At-Talaq", nameArabic: "الطلاق", versesCount: 12, revelationType: "medinan" },
  { number: 66, name: "At-Tahrim", nameArabic: "التحريم", versesCount: 12, revelationType: "medinan" },
  { number: 67, name: "Al-Mulk", nameArabic: "الملك", versesCount: 30, revelationType: "meccan" },
  { number: 68, name: "Al-Qalam", nameArabic: "القلم", versesCount: 52, revelationType: "meccan" },
  { number: 69, name: "Al-Haqqah", nameArabic: "الحاقة", versesCount: 52, revelationType: "meccan" },
  { number: 70, name: "Al-Ma'arij", nameArabic: "المعارج", versesCount: 44, revelationType: "meccan" },
  { number: 71, name: "Nuh", nameArabic: "نوح", versesCount: 28, revelationType: "meccan" },
  { number: 72, name: "Al-Jinn", nameArabic: "الجن", versesCount: 28, revelationType: "meccan" },
  { number: 73, name: "Al-Muzzammil", nameArabic: "المزمل", versesCount: 20, revelationType: "meccan" },
  { number: 74, name: "Al-Muddaththir", nameArabic: "المدثر", versesCount: 56, revelationType: "meccan" },
  { number: 75, name: "Al-Qiyamah", nameArabic: "القيامة", versesCount: 40, revelationType: "meccan" },
  { number: 76, name: "Al-Insan", nameArabic: "الإنسان", versesCount: 31, revelationType: "medinan" },
  { number: 77, name: "Al-Mursalat", nameArabic: "المرسلات", versesCount: 50, revelationType: "meccan" },
  { number: 78, name: "An-Naba", nameArabic: "النبإ", versesCount: 40, revelationType: "meccan" },
  { number: 79, name: "An-Nazi'at", nameArabic: "النازعات", versesCount: 46, revelationType: "meccan" },
  { number: 80, name: "Abasa", nameArabic: "عبس", versesCount: 42, revelationType: "meccan" },
  { number: 81, name: "At-Takwir", nameArabic: "التكوير", versesCount: 29, revelationType: "meccan" },
  { number: 82, name: "Al-Infitar", nameArabic: "الانفطار", versesCount: 19, revelationType: "meccan" },
  { number: 83, name: "Al-Mutaffifin", nameArabic: "المطففين", versesCount: 36, revelationType: "meccan" },
  { number: 84, name: "Al-Inshiqaq", nameArabic: "الانشقاق", versesCount: 25, revelationType: "meccan" },
  { number: 85, name: "Al-Buruj", nameArabic: "البروج", versesCount: 22, revelationType: "meccan" },
  { number: 86, name: "At-Tariq", nameArabic: "الطارق", versesCount: 17, revelationType: "meccan" },
  { number: 87, name: "Al-A'la", nameArabic: "الأعلى", versesCount: 19, revelationType: "meccan" },
  { number: 88, name: "Al-Ghashiyah", nameArabic: "الغاشية", versesCount: 26, revelationType: "meccan" },
  { number: 89, name: "Al-Fajr", nameArabic: "الفجر", versesCount: 30, revelationType: "meccan" },
  { number: 90, name: "Al-Balad", nameArabic: "البلد", versesCount: 20, revelationType: "meccan" },
  { number: 91, name: "Ash-Shams", nameArabic: "الشمس", versesCount: 15, revelationType: "meccan" },
  { number: 92, name: "Al-Layl", nameArabic: "الليل", versesCount: 21, revelationType: "meccan" },
  { number: 93, name: "Ad-Duhaa", nameArabic: "الضحى", versesCount: 11, revelationType: "meccan" },
  { number: 94, name: "Ash-Sharh", nameArabic: "الشرح", versesCount: 8, revelationType: "meccan" },
  { number: 95, name: "At-Tin", nameArabic: "التين", versesCount: 8, revelationType: "meccan" },
  { number: 96, name: "Al-Alaq", nameArabic: "العلق", versesCount: 19, revelationType: "meccan" },
  { number: 97, name: "Al-Qadr", nameArabic: "القدر", versesCount: 5, revelationType: "meccan" },
  { number: 98, name: "Al-Bayyinah", nameArabic: "البينة", versesCount: 8, revelationType: "medinan" },
  { number: 99, name: "Az-Zalzalah", nameArabic: "الزلزلة", versesCount: 8, revelationType: "medinan" },
  { number: 100, name: "Al-Adiyat", nameArabic: "العاديات", versesCount: 11, revelationType: "meccan" },
  { number: 101, name: "Al-Qari'ah", nameArabic: "القارعة", versesCount: 11, revelationType: "meccan" },
  { number: 102, name: "At-Takathur", nameArabic: "التكاثر", versesCount: 8, revelationType: "meccan" },
  { number: 103, name: "Al-Asr", nameArabic: "العصر", versesCount: 3, revelationType: "meccan" },
  { number: 104, name: "Al-Humazah", nameArabic: "الهمزة", versesCount: 9, revelationType: "meccan" },
  { number: 105, name: "Al-Fil", nameArabic: "الفيل", versesCount: 5, revelationType: "meccan" },
  { number: 106, name: "Quraysh", nameArabic: "قريش", versesCount: 4, revelationType: "meccan" },
  { number: 107, name: "Al-Ma'un", nameArabic: "الماعون", versesCount: 7, revelationType: "meccan" },
  { number: 108, name: "Al-Kawthar", nameArabic: "الكوثر", versesCount: 3, revelationType: "meccan" },
  { number: 109, name: "Al-Kafirun", nameArabic: "الكافرون", versesCount: 6, revelationType: "meccan" },
  { number: 110, name: "An-Nasr", nameArabic: "النصر", versesCount: 3, revelationType: "medinan" },
  { number: 111, name: "Al-Masad", nameArabic: "المسد", versesCount: 5, revelationType: "meccan" },
  { number: 112, name: "Al-Ikhlas", nameArabic: "الإخلاص", versesCount: 4, revelationType: "meccan" },
  { number: 113, name: "Al-Falaq", nameArabic: "الفلق", versesCount: 5, revelationType: "meccan" },
  { number: 114, name: "An-Nas", nameArabic: "الناس", versesCount: 6, revelationType: "meccan" },
];

// Sourates populaires pour mémorisation
export const POPULAR_SURAHS = [1, 36, 55, 56, 67, 78, 112, 113, 114];

// Juz Amma (30ème juz) - sourates courtes idéales pour débutants
export const JUZ_AMMA_SURAHS = Array.from({ length: 37 }, (_, i) => 78 + i).filter(n => n <= 114);
